#!/usr/bin/python
######################################################
#Alex Hortin
#PA1
#CPTS 425 
#March 2009
#charFreqGen
######################################################
import sys

if "-i" not in sys.argv or "-o" not in sys.argv: #checking for the proper arguments
	print "...usage: -i input_file -o output_file -t top_count"
	exit(1)
if "-t" not in sys.argv: top_count = 5
print "...charecter frequency count"
for arg in enumerate(sys.argv):
	if sys.argv[arg[0]] == "-i":#found the infile flag
		print "...opening '", sys.argv[arg[0]+1], "' for read"
		f_read = open((sys.argv[arg[0]+1]), 'r')
	if sys.argv[arg[0]] == "-o":#found the outfile flag
		print "...opening '", sys.argv[arg[0]+1], "' for write"
		f_write = open((sys.argv[arg[0]+1]), 'w')
	if sys.argv[arg[0]] == "-t":#found the top count flag
		top_count = int(sys.argv[arg[0]+1])
file_as_string = ""
for line in f_read: file_as_string+=line#appending all the lines into a string to take advantage of python's string library
freqlist = []
file_as_string = file_as_string.lower()
for i in range(95): #for all the possible characters
	freqlist.append(( float(file_as_string.count(chr(i+32)))/float(len(file_as_string)),chr(i+32)  ))#build a list of the tuples (occurance,char)
for i in freqlist: f_write.write(str(i[0])+" "+str(i[1])+" \n")#writing the freq list to the outfile
freqlist = sorted( freqlist)#sorting the array
for i in range(top_count): print (str(freqlist[(-1*i-1)][0])+" "+str(freqlist[(-1*i-1)][1])+" \n")#printing out the sorted results to the user based on top_count

